# Generated by Django 5.1 on 2024-09-05 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AsymmetricApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesforhomepage',
            old_name='deteils',
            new_name='details',
        ),
    ]
