# Generated by Django 5.1 on 2024-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsymmetricApp', '0002_rename_deteils_servicesforhomepage_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudiesDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=66)),
                ('image', models.ImageField(upload_to='case_studies/')),
                ('details', models.TextField()),
                ('service_type', models.CharField(choices=[('Branding', 'Branding'), ('Digital', 'Digital'), ('Ecommerce', 'Ecommerce'), ('Print', 'Print')], default='Branding', max_length=10)),
            ],
        ),
    ]
