# Generated by Django 5.1 on 2024-09-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AsymmetricApp', '0005_company_companyview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyview',
            name='company_image',
            field=models.ImageField(upload_to='aaaa'),
        ),
    ]
